### ISSUE TITLE
Implementar CQRS

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/stamp_classifier_step#12]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/stamp_classifier_step/issues/13
- [ ] https://github.com/alercebroker/stamp_classifier_step/issues/15
- [ ] https://github.com/alercebroker/stamp_classifier_step/issues/14
- [ ] https://github.com/alercebroker/kubernetes_pipeline/issues/32
```

![Image](https://user-images.githubusercontent.com/18015991/216419656-b1358df1-ede2-4639-aa9e-b416c55a4118.png)
