### ISSUE TITLE
Crear ATLAS stamp classifier step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/stamp_classifier_step#2]
```[tasklist]
### Tasks
- [x] Implementar CQRS
- [x] Agregar test unitarios
- [x] Agregar test de integración
- [x] Crear deployment en repo kubernetes_pipeline
```
