### ISSUE TITLE
Actualizar para alerta genérica

### ISSUE THREAD

**Issue by pcastelln** [alercebroker/stamp_classifier_step#30]
```[tasklist]
### Tasks
- [x] Revisar la cobertura de test unitarios
- [x] Revisar cobertura para  integración
- [x] Evaluar posibles efectos del cambio de esquema
```
